name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Volta(Node)
        uses: volta-cli/action@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup tree-sitter
        run: npm i -g tree-sitter-cli

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun typecheck

      - name: Tree-sitter tests
        run: tree-sitter test

      - name: Node binding tests
        run: bun test

      - name: Regex harness
        run: bun test:regex
